### ISSUE TITLE
3C Newsletter

### ISSUE THREAD

**Issue by wlovell** [skimbro1/CCC#4]
To Rob, a weekly newsletter is a TOP Priority, so I'm trying to think this through. One essential step is to make sure we have a current list of members. Here's a Word Document. I'll also send a spreadsheet. 
[3C Church Directory Booklet 2017.docx](https://github.com/skimbro1/CCC/files/849152/3C.Church.Directory.Booklet.2017.docx)

**Comment by skimbro1** [comment]
@wlovell - that's one of the topics I want to discuss as well.  From a "workflow" standpoint, the website is designed thus:

1.  Members can be added and people can "self-maintain" their information.  Some won't be able to due to age, lack of access to internet, etc.

2.  After creating members they can be assigned to groups.  We can have a "Newsletter" group, or an "all church group" or a "visitors" group or whatever.

2.  Once that's done, there is a "Newsletter" function that will allow you to blast out an email to anyone you want.  

See this help page for detail:  http://layouts.ekklesia360.com/newsletters/1/

**Comment by skimbro1** [comment]
@wlovell - I've been thinking about this and I'd like to look into the Members function a bit more and figure out how to allow people to maintain their information.  I can set up a time to discuss with Ekklesia360 tomorrow or Monday.

**Comment by skimbro1** [comment]
@wlovell - For the time being we'll have to use the plain Newsletter template that is provided with may or may not allow for a header image.

Ekklesia360 sells what they call Newsletter Layout 1 or 2 for $250.00.

You can see what they look like here:  http://layouts.ekklesia360.com/newsletters/1/
